In [17]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:0000@localhost:5432/insurance_company')

df_policy_keys = pd.read_sql("SELECT policy_key FROM curated.curated_policies", engine)
df_product_keys = pd.read_sql("SELECT product_key FROM curated.curated_products", engine)
df_vehicle_keys = pd.read_sql("SELECT vehicle_key FROM curated.curated_vehicles", engine)
df_agency_keys = pd.read_sql("SELECT agency_key FROM curated.curated_agencies", engine)
df_policyholder_keys = pd.read_sql("SELECT policyholder_key FROM curated.curated_policyholders", engine)
df_date_keys = pd.read_sql("SELECT date_key FROM curated.curated_dates", engine)
df_premimum_amount = pd.read_sql("SELECT premium_amount AS policy_sales_amount FROM curated.curated_policies",engine)

fuck = pd.concat([df_policy_keys,df_product_keys,df_vehicle_keys,df_agency_keys,df_policyholder_keys,df_date_keys,df_premimum_amount], axis=1)

df_policy_sales = pd.read_sql("SELECT policy_key, product_key, vehicle_key, agency_key, policyholder_key, date_key, policy_sales_amount FROM insurance_dw.policy_sales_fact", engine)

merged_df = fuck.merge(df_policy_sales, indicator=True, how='left')
merged_df
new_df = merged_df[merged_df['_merge'] == 'left_only']
goal = new_df.drop(columns='_merge')

goal.to_sql('policy_sales_fact', engine, schema = 'insurance_dw', if_exists='append', index=False)

91

In [14]:
pls = pd.read_sql("SELECT * FROM insurance_dw.policy_sales_fact", engine)
pls.tail(20)

,sales_key,policy_key,product_key,agency_key,date_key,policyholder_key,vehicle_key,policy_sales_amount
120,121,72.0,72.0,72.0,72.0,72.0,72.0,2918.0
121,122,73.0,73.0,73.0,73.0,73.0,73.0,1135.0
122,123,74.0,74.0,74.0,74.0,74.0,74.0,1715.0
123,124,75.0,75.0,75.0,75.0,75.0,75.0,1665.0
124,125,76.0,76.0,76.0,76.0,76.0,76.0,2758.0
125,126,77.0,77.0,77.0,77.0,77.0,77.0,1027.0
126,127,78.0,78.0,78.0,78.0,78.0,78.0,2642.0
127,128,79.0,79.0,79.0,79.0,79.0,79.0,1263.0
128,129,80.0,80.0,80.0,80.0,80.0,80.0,1081.0
129,130,81.0,81.0,81.0,81.0,81.0,81.0,2637.0
130,131,82.0,82.0,82.0,82.0,82.0,82.0,1233.0
131,132,83.0,83.0,83.0,83.0,83.0,83.0,1745.0
132,133,84.0,84.0,84.0,84.0,84.0,84.0,1248.0
133,134,85.0,85.0,85.0,85.0,85.0,85.0,1501.0
134,135,86.0,86.0,86.0,86.0,86.0,86.0,1554.0
135,136,87.0,87.0,87.0,87.0,87.0,87.0,2907.0
136,137,88.0,88.0,88.0,88.0,88.0,88.0,1877.0
137,138,89.0,89.0,89.0,89.0,89.0,89.0,2228.0
138,139,90.0,90.0,90.0,90.0,90.0,90.0,1405.0
139,140,91.0,91.0,91.0,91.0,91.0,91.0,1955.0